[versions]
spring = "6.2.3"
jackson = "2.18.2"
springBoot = "3.4.3"
junit = "5.10.0"
shadow-plugin = "8.1.1"

[libraries]
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
jackson-csv = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-csv", version.ref = "jackson" }
spring-boot-aop = { module = "org.springframework.boot:spring-boot-starter-aop", version.ref = "springBoot" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow-plugin" }