
INSERT INTO genres (name) VALUES
('Fantasy'),
('Science Fiction'),
('Horror'),
('Mystery'),
('Thriller'),
('Romance'),
('Historical'),
('Non-Fiction'),
('Biography'),
('Self-Help'),
('Adventure'),
('Young Adult'),
('Children''s'),
('Drama'),
('Poetry'),
('Classic'),
('Dystopian'),
('Comedy'),
('Crime'),
('Philosophy');

INSERT INTO authors (name) VALUES
('J.R.R. Tolkien'),
('George R.R. Martin'),
('Patrick Rothfuss'),
('Frank Herbert'),
('Andy Weir'),
('William Gibson'),
('Stephen King'),
('Bram Stoker'),
('Shirley Jackson'),
('Gillian Flynn'),
('Stieg Larsson'),
('Agatha Christie'),
('Alex Michaelides'),
('Dan Brown'),
('Robert Ludlum'),
('Jane Austen'),
('Diana Gabaldon'),
('Nicholas Sparks'),
('Markus Zusak'),
('Anthony Doerr'),
('Hilary Mantel'),
('Yuval Noah Harari'),
('Rebecca Skloot'),
('Jon Krakauer'),
('Walter Isaacson'),
('Anne Frank'),
('Malala Yousafzai'),
('James Clear'),
('Stephen R. Covey'),
('Dale Carnegie');

INSERT INTO books (title, description, genre_id, pages, rating) VALUES
('The Hobbit', 'A reluctant hobbit embarks on a grand adventure to win a share of a dragon''s treasure.', 1, 310, 4.7),
('A Game of Thrones', 'Noble families fight for control of the mythical land of Westeros.', 1, 694, 4.4),
('The Name of the Wind', 'The story of Kvothe, an adventurer and musician with a dark past.', 1, 662, 4.5),
('Dune', 'A young man becomes a messiah to a desert people in a galactic empire.', 2, 412, 4.6),
('The Martian', 'An astronaut must survive alone on Mars after being left behind.', 2, 369, 4.4),
('Neuromancer', 'A washed-up computer hacker is hired for one last job in cyberspace.', 2, 271, 4.0),
('The Shining', 'A family heads to an isolated hotel where a sinister presence influences the father.', 3, 447, 4.2),
('Dracula', 'The classic vampire story told through a series of letters and diary entries.', 3, 418, 4.0),
('The Haunting of Hill House', 'Four people stay in a notoriously haunted house to investigate.', 3, 246, 4.1),
('Gone Girl', 'A woman disappears on her wedding anniversary, and her husband becomes the prime suspect.', 4, 415, 4.1),
('The Girl with the Dragon Tattoo', 'A journalist and a hacker investigate a 40-year-old disappearance.', 4, 465, 4.2),
('Murder on the Orient Express', 'Hercule Poirot investigates a murder on a snowbound train.', 4, 256, 4.3),
('The Silent Patient', 'A criminal psychotherapist tries to unravel why his patient shot her husband.', 5, 323, 4.2),
('The Da Vinci Code', 'A symbologist and cryptologist try to solve a murder in the Louvre.', 5, 454, 3.8),
('The Bourne Identity', 'A man with amnesia discovers he''s a highly trained assassin.', 5, 523, 4.0),
('Pride and Prejudice', 'The romantic tensions between Elizabeth Bennet and Mr. Darcy in Regency England.', 6, 279, 4.3),
('Outlander', 'A WWII nurse is transported back to 18th century Scotland and falls in love.', 6, 850, 4.2),
('The Notebook', 'A poor young man falls in love with a rich young woman in 1940s South Carolina.', 6, 214, 4.1),
('The Book Thief', 'A young girl steals books in Nazi Germany, narrated by Death.', 7, 552, 4.4),
('All the Light We Cannot See', 'The paths of a blind French girl and a German boy collide in WWII.', 7, 531, 4.3),
('Wolf Hall', 'The rise of Thomas Cromwell in the court of Henry VIII.', 7, 604, 4.0),
('Sapiens', 'A brief history of humankind from evolution to modern society.', 8, 443, 4.4),
('The Immortal Life of Henrietta Lacks', 'The story of a woman whose cells were used for scientific research without her knowledge.', 8, 370, 4.1),
('Into the Wild', 'The true story of a young man who gave up everything to live in the Alaskan wilderness.', 8, 207, 4.0),
('Steve Jobs', 'The authorized biography of Apple''s visionary co-founder.', 9, 656, 4.2),
('The Diary of a Young Girl', 'The diary of Anne Frank while hiding from the Nazis in WWII.', 9, 283, 4.2),
('I Am Malala', 'The story of Malala Yousafzai, who stood up for girls'' education in Pakistan.', 9, 327, 4.3),
('Atomic Habits', 'A guide to building good habits and breaking bad ones.', 10, 306, 4.4),
('The 7 Habits of Highly Effective People', 'Principles for personal and professional effectiveness.', 10, 381, 4.1),
('How to Win Friends and Influence People', 'Classic advice for improving social skills and relationships.', 10, 288, 4.2);

INSERT INTO book_authors (book_id, author_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15),
(16, 16),
(17, 17),
(18, 18),
(19, 19),
(20, 20),
(21, 21),
(22, 22),
(23, 23),
(24, 24),
(25, 25),
(26, 26),
(27, 27),
(28, 28),
(29, 29),
(30, 30),
(4, 1),
(12, 13),
(18, 19);
